.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 01/05/2017               \" DATE 
.Dt pocket-piap-extras-rpi2-us 7      \" Program name and manual section number 
.Os rasbian
.Sh NAME                 \" Section Header - required - don't modify 
.Nm pocket-piap-extras-rpi2-us
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.\" Use .Nm macro to designate other names for the documented program.
.Nd Extras for the Pocket AP control utility.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
.No i Ns s No some extra tweaks to Pocket PiAP for raspberryPi 2 Ns .
.Bl -tag -width -indent  \" Differs from above in tag removed 
.It disables blutooth deamon intended for model 3 boards
.It configures the timezone via /etc/cron.hourly/fix_timezone
.El                      \" Ends the list
.Pp                     
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "/Users/joeuser/Library/really_long_file_name" -compact
.It Pa /etc/cron.hourly/fix_timezone
fix_timezone configures the timezone t Ns o No U Ns S No Pacific
.It Pa /etc/cron.hourly/disable_bluetooth
FILE_2 disable bluetooth deamon
.El
.Pp
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr rfkill 1 , 
.Xr bluez 1
