#! /bin/bash --posix
# this is part of pocket-piap-extras-rpi2-us
ulimit -t 30
pkill bluez 2>/dev/null > /dev/null || true 
test -x /etc/init.d/bluetooth || exit 0 ;
/etc/init.d/bluetooth stop 2>/dev/null ; wait ;
pkill bluez 2>/dev/null > /dev/null || true 
test -x /usr/sbin/rfkill || exit 0 ;
/usr/sbin/rfkill block bluetooth 2>/dev/null > /dev/null ; wait ;

exit 0 ; 
